# Generated by Django 5.1.6 on 2025-03-17 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('quotation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('type', models.TextField(choices=[('Project Based', 'Project Based'), ('Non Project Based', 'Non Project Based'), ('Service', 'Service')])),
                ('status', models.TextField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')])),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('salesresp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.employee')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItems',
            fields=[
                ('qitems_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.product')),
                ('quotation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.quotation')),
            ],
        ),
    ]
