# Generated by Django 5.1.6 on 2025-03-17 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='salesresp_id',
            new_name='salesrep_id',
        ),
    ]
