# Generated by Django 5.1.6 on 2025-03-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_rename_salesresp_id_quotation_salesrep_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quotationitems',
            table='quotation_quotationitems',
        ),
    ]
