# Generated by Django 5.1.6 on 2025-03-17 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_alter_quotationitems_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='type',
            field=models.TextField(choices=[('Project Based', 'Project Based'), ('Non-Project Based', 'Non Project Based'), ('Service', 'Service')]),
        ),
        migrations.AlterField(
            model_name='quotationitems',
            name='quotation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotation.quotation'),
        ),
        migrations.AlterModelTable(
            name='quotationitems',
            table=None,
        ),
    ]
