# Generated by Django 5.1.6 on 2025-03-17 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_gl_account_id'),
        ('misc', '0002_product_stock'),
        ('quotation', '0004_alter_quotation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='salesrep_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.employee'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.TextField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending'),
        ),
        migrations.AlterField(
            model_name='quotationitems',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.product'),
        ),
    ]
