# Generated by Django 5.1.6 on 2025-03-18 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0006_alter_quotation_date_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date_issued',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 12, 8, 9, 414529)),
        ),
    ]
