# Generated by Django 5.1.6 on 2025-03-17 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email_address', models.TextField(max_length=255, unique=True)),
                ('phone_number', models.TextField(max_length=20)),
                ('address_line1', models.TextField(max_length=255)),
                ('address_line2', models.TextField(max_length=255)),
                ('city', models.TextField(max_length=100)),
                ('postal_code', models.TextField(max_length=20)),
                ('country', models.TextField(max_length=100)),
                ('customer_type', models.TextField(choices=[('Lead', 'Lead'), ('Prospect', 'Prospect'), ('Client', 'Client')])),
                ('status', models.TextField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')])),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gl_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.generalledgeraccounts')),
            ],
        ),
    ]
