# Generated by Django 5.1.6 on 2025-03-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address_line2',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
