# Generated by Django 5.1.6 on 2025-03-17 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_city_alter_customer_country_and_more'),
        ('misc', '0002_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gl_account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.generalledgeraccounts'),
        ),
    ]
