--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: CRM_campaigncontacts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."CRM_campaigncontacts" (
    id bigint NOT NULL,
    campaign_id_id integer NOT NULL,
    lead_id_id integer,
    response_status text NOT NULL
);


ALTER TABLE public."CRM_campaigncontacts" OWNER TO postgres;

--
-- Name: CRM_campaigncontacts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."CRM_campaigncontacts" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CRM_campaigncontacts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: CRM_campaigns; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."CRM_campaigns" (
    campaign_id integer NOT NULL,
    campaign_name character varying(255) NOT NULL,
    type text NOT NULL,
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone NOT NULL,
    status text NOT NULL
);


ALTER TABLE public."CRM_campaigns" OWNER TO postgres;

--
-- Name: CRM_campaigns_campaign_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."CRM_campaigns" ALTER COLUMN campaign_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CRM_campaigns_campaign_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: CRM_leads; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."CRM_leads" (
    lead_id integer NOT NULL,
    lead_name character varying(255) NOT NULL,
    lead_email character varying(255) NOT NULL,
    lead_phonenum character varying(20) NOT NULL,
    source text NOT NULL,
    status text NOT NULL,
    salesrep_id_id bigint
);


ALTER TABLE public."CRM_leads" OWNER TO postgres;

--
-- Name: CRM_leads_lead_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."CRM_leads" ALTER COLUMN lead_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CRM_leads_lead_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: CRM_opportunities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."CRM_opportunities" (
    opportunity_id integer NOT NULL,
    estimated_value numeric(10,2) NOT NULL,
    expected_closed_date timestamp with time zone NOT NULL,
    stage text NOT NULL,
    status text NOT NULL,
    description text,
    reason_lost text,
    created_at timestamp with time zone NOT NULL,
    customer_id_id bigint,
    partner_id_id integer,
    salesrep_id_id bigint
);


ALTER TABLE public."CRM_opportunities" OWNER TO postgres;

--
-- Name: CRM_opportunities_opportunity_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."CRM_opportunities" ALTER COLUMN opportunity_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CRM_opportunities_opportunity_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: CRM_ticket; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."CRM_ticket" (
    ticket_id integer NOT NULL,
    subject character varying(255) NOT NULL,
    description text NOT NULL,
    status text NOT NULL,
    priority text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    customer_id_id bigint NOT NULL,
    salesrep_id_id bigint
);


ALTER TABLE public."CRM_ticket" OWNER TO postgres;

--
-- Name: CRM_ticket_ticket_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."CRM_ticket" ALTER COLUMN ticket_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CRM_ticket_ticket_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: CRM_ticketconvo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."CRM_ticketconvo" (
    convo_id integer NOT NULL,
    content character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    ticket_id_id integer NOT NULL
);


ALTER TABLE public."CRM_ticketconvo" OWNER TO postgres;

--
-- Name: CRM_ticketconvo_convo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."CRM_ticketconvo" ALTER COLUMN convo_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CRM_ticketconvo_convo_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: agreement_blanketagreement; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.agreement_blanketagreement (
    agreement_id integer NOT NULL,
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone NOT NULL,
    total_value numeric(10,2) NOT NULL,
    status text NOT NULL,
    description character varying(255) NOT NULL,
    signed_date timestamp with time zone NOT NULL,
    agreement_method text NOT NULL,
    customer_id_id bigint NOT NULL,
    salesrep_id_id bigint NOT NULL
);


ALTER TABLE public.agreement_blanketagreement OWNER TO postgres;

--
-- Name: agreement_blanketagreement_agreement_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.agreement_blanketagreement ALTER COLUMN agreement_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agreement_blanketagreement_agreement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: agreement_blanketagreementitems; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.agreement_blanketagreementitems (
    agreement_items_id integer NOT NULL,
    agreed_quantity integer NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    agreement_id_id integer NOT NULL,
    product_id_id bigint NOT NULL
);


ALTER TABLE public.agreement_blanketagreementitems OWNER TO postgres;

--
-- Name: agreement_blanketagreementitems_agreement_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.agreement_blanketagreementitems ALTER COLUMN agreement_items_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agreement_blanketagreementitems_agreement_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_customer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customer_customer (
    customer_id bigint NOT NULL,
    email_address character varying(255) NOT NULL,
    phone_number character varying(20) NOT NULL,
    address_line1 text NOT NULL,
    address_line2 text,
    city character varying(100) NOT NULL,
    postal_code character varying(20) NOT NULL,
    country character varying(100) NOT NULL,
    customer_type text NOT NULL,
    status text NOT NULL,
    debt numeric(10,2) NOT NULL,
    gl_account_id_id bigint,
    name character varying(255) NOT NULL
);


ALTER TABLE public.customer_customer OWNER TO postgres;

--
-- Name: customer_customer_customer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.customer_customer ALTER COLUMN customer_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_customer_customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: misc_businesspartnermaster; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.misc_businesspartnermaster (
    partner_id integer NOT NULL,
    partner_name character varying(255) NOT NULL
);


ALTER TABLE public.misc_businesspartnermaster OWNER TO postgres;

--
-- Name: misc_businesspartnermaster_partner_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.misc_businesspartnermaster ALTER COLUMN partner_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.misc_businesspartnermaster_partner_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: misc_chartofaccounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.misc_chartofaccounts (
    account_code bigint NOT NULL,
    account_name text NOT NULL
);


ALTER TABLE public.misc_chartofaccounts OWNER TO postgres;

--
-- Name: misc_chartofaccounts_account_code_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.misc_chartofaccounts ALTER COLUMN account_code ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.misc_chartofaccounts_account_code_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: misc_employee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.misc_employee (
    employee_id bigint NOT NULL,
    first_name text NOT NULL,
    last_name text NOT NULL,
    email text NOT NULL,
    phone text NOT NULL,
    job_title text NOT NULL
);


ALTER TABLE public.misc_employee OWNER TO postgres;

--
-- Name: misc_employee_employee_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.misc_employee ALTER COLUMN employee_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.misc_employee_employee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: misc_generalledgeraccounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.misc_generalledgeraccounts (
    gl_account_id bigint NOT NULL,
    account_name text NOT NULL,
    account_code_id bigint NOT NULL
);


ALTER TABLE public.misc_generalledgeraccounts OWNER TO postgres;

--
-- Name: misc_generalledgeraccounts_gl_account_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.misc_generalledgeraccounts ALTER COLUMN gl_account_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.misc_generalledgeraccounts_gl_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: misc_goodsissue; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.misc_goodsissue (
    goods_issue_id integer NOT NULL,
    issue_date timestamp with time zone NOT NULL
);


ALTER TABLE public.misc_goodsissue OWNER TO postgres;

--
-- Name: misc_goodsissue_goods_issue_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.misc_goodsissue ALTER COLUMN goods_issue_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.misc_goodsissue_goods_issue_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: misc_policies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.misc_policies (
    policy_id bigint NOT NULL,
    policy_name text NOT NULL,
    description text NOT NULL,
    effective_date timestamp with time zone NOT NULL
);


ALTER TABLE public.misc_policies OWNER TO postgres;

--
-- Name: misc_policies_policy_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.misc_policies ALTER COLUMN policy_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.misc_policies_policy_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: misc_product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.misc_product (
    product_id bigint NOT NULL,
    product_name text NOT NULL,
    description text NOT NULL,
    unit_of_measure text NOT NULL,
    policy_id_id bigint NOT NULL,
    stock integer NOT NULL
);


ALTER TABLE public.misc_product OWNER TO postgres;

--
-- Name: misc_product_product_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.misc_product ALTER COLUMN product_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.misc_product_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: misc_reworkorder; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.misc_reworkorder (
    rework_id integer NOT NULL,
    rework_status text NOT NULL,
    rework_date timestamp with time zone NOT NULL,
    expected_completion timestamp with time zone NOT NULL
);


ALTER TABLE public.misc_reworkorder OWNER TO postgres;

--
-- Name: misc_reworkorder_rework_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.misc_reworkorder ALTER COLUMN rework_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.misc_reworkorder_rework_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_orders (
    order_id integer NOT NULL,
    order_date timestamp with time zone NOT NULL,
    order_status text NOT NULL,
    order_type text NOT NULL,
    agreement_id_id integer,
    customer_id_id bigint NOT NULL,
    goods_issue_id_id integer NOT NULL,
    quotation_id_id bigint,
    rework_id_id integer NOT NULL,
    salesrep_id_id bigint
);


ALTER TABLE public.order_orders OWNER TO postgres;

--
-- Name: order_orders_order_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.order_orders ALTER COLUMN order_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_orders_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quotation_quotation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quotation_quotation (
    quotation_id bigint NOT NULL,
    date_issued timestamp with time zone NOT NULL,
    total_amount numeric(10,2) NOT NULL,
    type text NOT NULL,
    status text NOT NULL,
    customer_id_id bigint,
    salesrep_id_id bigint
);


ALTER TABLE public.quotation_quotation OWNER TO postgres;

--
-- Name: quotation_quotation_quotation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.quotation_quotation ALTER COLUMN quotation_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quotation_quotation_quotation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quotation_quotationitems; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quotation_quotationitems (
    qitems_id bigint NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    total_price numeric(10,2) NOT NULL,
    product_id_id bigint,
    quotation_id_id bigint NOT NULL
);


ALTER TABLE public.quotation_quotationitems OWNER TO postgres;

--
-- Name: quotation_quotationitems_qitems_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.quotation_quotationitems ALTER COLUMN qitems_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quotation_quotationitems_qitems_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: CRM_campaigncontacts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."CRM_campaigncontacts" (id, campaign_id_id, lead_id_id, response_status) FROM stdin;
31	31	41	Interested
32	31	42	Not Interested
33	32	43	Pending
34	33	44	Interested
35	34	45	Not Interested
36	35	46	Interested
37	36	47	Pending
38	37	48	Not Interested
39	38	49	Interested
40	39	50	Pending
\.


--
-- Data for Name: CRM_campaigns; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."CRM_campaigns" (campaign_id, campaign_name, type, start_date, end_date, status) FROM stdin;
31	New Medical Equipment Launch	Email	2025-04-01 08:00:00+08	2025-04-15 23:59:59+08	Planned
32	Exclusive Discount for Clinics	Email	2025-03-20 08:00:00+08	2025-04-05 23:59:59+08	Active
33	Hospital Procurement Webinar	Email	2025-03-10 08:00:00+08	2025-03-15 23:59:59+08	Completed
34	Free Sample: Surgical Masks	Email	2025-04-10 08:00:00+08	2025-04-20 23:59:59+08	Planned
35	Loyalty Rewards for Pharmacies	Email	2025-03-01 08:00:00+08	2025-03-31 23:59:59+08	Active
36	Medical Device Compliance Update	Email	2025-02-20 08:00:00+08	2025-03-05 23:59:59+08	Completed
37	Healthcare Expo Invitation	Email	2025-04-05 08:00:00+08	2025-04-25 23:59:59+08	Planned
38	Exclusive Bulk Order Offer	Email	2025-03-15 08:00:00+08	2025-03-30 23:59:59+08	Active
39	New FDA-Approved Products	Email	2025-02-10 08:00:00+08	2025-02-28 23:59:59+08	Completed
40	Emergency Medical Supplies Sale	Email	2025-04-12 08:00:00+08	2025-04-22 23:59:59+08	Planned
\.


--
-- Data for Name: CRM_leads; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."CRM_leads" (lead_id, lead_name, lead_email, lead_phonenum, source, status, salesrep_id_id) FROM stdin;
41	Dr. Jose Martinez	jose.martinez@healthclinic.com	+63-917-555-1001	Referral	Contacted	31
42	Maria Santos	maria.santos@meditechph.com	+63-917-555-1002	Website	Qualified	32
43	Carlos Dela Cruz	carlos.dc@lifelinediag.com	+63-917-555-1003	Cold Call	New	33
44	Anna Reyes	anna.reyes@biopharmph.com	+63-917-555-1004	Email	Converted	31
45	Rafael Gonzales	rafael.gonzales@pharmasolutions.com	+63-917-555-1005	Referral	Lost	31
46	Isabel Flores	isabel.flores@mediserveph.com	+63-917-555-1006	Website	Qualified	32
47	Michael Torres	michael.torres@healthplus.com.ph	+63-917-555-1007	Cold Call	Contacted	33
48	Elena Cruz	elena.cruz@philmedpharma.com	+63-917-555-1008	Email	Converted	33
49	Luis Navarro	luis.navarro@vitalcareph.com	+63-917-555-1009	Referral	Qualified	32
50	Patricia Mendoza	patricia.mendoza@pediacareph.com	+63-917-555-1010	Website	New	33
\.


--
-- Data for Name: CRM_opportunities; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."CRM_opportunities" (opportunity_id, estimated_value, expected_closed_date, stage, status, description, reason_lost, created_at, customer_id_id, partner_id_id, salesrep_id_id) FROM stdin;
23	250000.00	2025-05-15 00:00:00+08	Prospecting	Open	Potential MRI scanner bulk order for hospital.	\N	2025-03-18 00:00:00+08	66	11	31
24	150000.00	2025-04-20 00:00:00+08	Negotiation	Open	Negotiating pricing for ventilators.	\N	2025-03-18 00:00:00+08	67	12	32
25	10000.00	2025-03-30 00:00:00+08	Closed	Won	Sold 500 surgical gloves.	\N	2025-03-18 00:00:00+08	68	10	33
26	75000.00	2025-06-01 00:00:00+08	Prospecting	Open	New client interested in defibrillators.	\N	2025-03-18 00:00:00+08	69	11	32
27	500000.00	2025-07-01 00:00:00+08	Negotiation	Lost	Large order for hospital beds.	Customer chose competitor.	2025-03-18 00:00:00+08	70	12	32
28	20000.00	2025-05-10 00:00:00+08	Closed	Won	Sold 200 syringes and 50 BP monitors.	\N	2025-03-18 00:00:00+08	66	10	31
29	8000.00	2025-04-25 00:00:00+08	Closed	Lost	Small clinic interested in ECG machine.	Budget constraints.	2025-03-18 00:00:00+08	67	11	32
30	95000.00	2025-05-20 00:00:00+08	Prospecting	Open	Potential deal for 3 new dialysis machines.	\N	2025-03-18 00:00:00+08	68	11	33
31	12000.00	2025-06-10 00:00:00+08	Negotiation	Open	Service maintenance contract for medical equipment.	\N	2025-03-18 00:00:00+08	69	12	33
32	180000.00	2025-06-30 00:00:00+08	Closed	Won	Bulk order for surgical gloves and hospital furniture.	\N	2025-03-18 00:00:00+08	70	10	31
\.


--
-- Data for Name: CRM_ticket; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."CRM_ticket" (ticket_id, subject, description, status, priority, created_at, customer_id_id, salesrep_id_id) FROM stdin;
11	MRI Machine Maintenance	Scheduled preventive maintenance for MRI scanner.	Open	High	2025-03-18 00:00:00+08	66	33
12	X-ray Calibration	X-ray machines require recalibration due to accuracy issues.	In Progress	Urgent	2025-03-18 00:00:00+08	67	32
13	Training Request - ECG Machine	Hospital staff need hands-on training for ECG machines.	Open	Medium	2025-03-18 00:00:00+08	68	31
14	Software Update - Ventilators	Need to update ventilator software for new compliance regulations.	Closed	Low	2025-03-18 00:00:00+08	69	32
15	Warranty Repair - Defibrillator	Defibrillator malfunction under warranty claim.	Open	High	2025-03-18 00:00:00+08	70	33
16	Technical Support - Ultrasound	Ultrasound machine displaying error code during operation.	In Progress	Medium	2025-03-18 00:00:00+08	66	33
17	Equipment Relocation Assistance	Need assistance in relocating an MRI scanner to another facility.	Closed	Low	2025-03-18 00:00:00+08	68	33
18	Hospital Bed Malfunction	Motorized hospital beds not adjusting properly.	Open	Urgent	2025-03-18 00:00:00+08	69	32
19	Battery Replacement - Portable Monitors	Request to replace batteries for 20 portable patient monitors.	In Progress	High	2025-03-18 00:00:00+08	67	31
20	On-Site Inspection - Operating Room Equipment	Request for technician visit to inspect all OR equipment.	Open	Medium	2025-03-18 00:00:00+08	70	32
\.


--
-- Data for Name: CRM_ticketconvo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."CRM_ticketconvo" (convo_id, content, created_at, ticket_id_id) FROM stdin;
11	Technician scheduled for MRI maintenance on April 5.	2025-03-18 00:00:00+08	11
12	Calibration tools dispatched, technician visit confirmed.	2025-03-18 00:00:00+08	12
13	ECG training session scheduled for March 15.	2025-03-18 00:00:00+08	13
14	Software update package sent, remote installation guide provided.	2025-03-18 00:00:00+08	14
15	Warranty repair approved, dispatching service team.	2025-03-18 00:00:00+08	15
16	Ultrasound troubleshooting guide sent, remote support scheduled.	2025-03-18 00:00:00+08	16
17	MRI relocation assistance team confirmed for March 20.	2025-03-18 00:00:00+08	17
18	Investigating motorized hospital bed issues, awaiting technician report.	2025-03-18 00:00:00+08	18
19	Battery order placed, estimated arrival March 10.	2025-03-18 00:00:00+08	19
20	On-site inspection scheduled for April 1, report to follow.	2025-03-18 00:00:00+08	20
\.


--
-- Data for Name: agreement_blanketagreement; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.agreement_blanketagreement (agreement_id, start_date, end_date, total_value, status, description, signed_date, agreement_method, customer_id_id, salesrep_id_id) FROM stdin;
\.


--
-- Data for Name: agreement_blanketagreementitems; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.agreement_blanketagreementitems (agreement_items_id, agreed_quantity, unit_price, agreement_id_id, product_id_id) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add blanket agreement	7	add_blanketagreement
26	Can change blanket agreement	7	change_blanketagreement
27	Can delete blanket agreement	7	delete_blanketagreement
28	Can view blanket agreement	7	view_blanketagreement
29	Can add blanket agreement items	8	add_blanketagreementitems
30	Can change blanket agreement items	8	change_blanketagreementitems
31	Can delete blanket agreement items	8	delete_blanketagreementitems
32	Can view blanket agreement items	8	view_blanketagreementitems
33	Can add campaigns	9	add_campaigns
34	Can change campaigns	9	change_campaigns
35	Can delete campaigns	9	delete_campaigns
36	Can view campaigns	9	view_campaigns
37	Can add leads	10	add_leads
38	Can change leads	10	change_leads
39	Can delete leads	10	delete_leads
40	Can view leads	10	view_leads
41	Can add campaign contacts	11	add_campaigncontacts
42	Can change campaign contacts	11	change_campaigncontacts
43	Can delete campaign contacts	11	delete_campaigncontacts
44	Can view campaign contacts	11	view_campaigncontacts
45	Can add opportunities	12	add_opportunities
46	Can change opportunities	12	change_opportunities
47	Can delete opportunities	12	delete_opportunities
48	Can view opportunities	12	view_opportunities
49	Can add ticket	13	add_ticket
50	Can change ticket	13	change_ticket
51	Can delete ticket	13	delete_ticket
52	Can view ticket	13	view_ticket
53	Can add ticket convo	14	add_ticketconvo
54	Can change ticket convo	14	change_ticketconvo
55	Can delete ticket convo	14	delete_ticketconvo
56	Can view ticket convo	14	view_ticketconvo
57	Can add customer	15	add_customer
58	Can change customer	15	change_customer
59	Can delete customer	15	delete_customer
60	Can view customer	15	view_customer
61	Can add orders	16	add_orders
62	Can change orders	16	change_orders
63	Can delete orders	16	delete_orders
64	Can view orders	16	view_orders
65	Can add quotation	17	add_quotation
66	Can change quotation	17	change_quotation
67	Can delete quotation	17	delete_quotation
68	Can view quotation	17	view_quotation
69	Can add quotation items	18	add_quotationitems
70	Can change quotation items	18	change_quotationitems
71	Can delete quotation items	18	delete_quotationitems
72	Can view quotation items	18	view_quotationitems
73	Can add chart of accounts	19	add_chartofaccounts
74	Can change chart of accounts	19	change_chartofaccounts
75	Can delete chart of accounts	19	delete_chartofaccounts
76	Can view chart of accounts	19	view_chartofaccounts
77	Can add employee	20	add_employee
78	Can change employee	20	change_employee
79	Can delete employee	20	delete_employee
80	Can view employee	20	view_employee
81	Can add policies	21	add_policies
82	Can change policies	21	change_policies
83	Can delete policies	21	delete_policies
84	Can view policies	21	view_policies
85	Can add general ledger accounts	22	add_generalledgeraccounts
86	Can change general ledger accounts	22	change_generalledgeraccounts
87	Can delete general ledger accounts	22	delete_generalledgeraccounts
88	Can view general ledger accounts	22	view_generalledgeraccounts
89	Can add product	23	add_product
90	Can change product	23	change_product
91	Can delete product	23	delete_product
92	Can view product	23	view_product
93	Can add business partner master	24	add_businesspartnermaster
94	Can change business partner master	24	change_businesspartnermaster
95	Can delete business partner master	24	delete_businesspartnermaster
96	Can view business partner master	24	view_businesspartnermaster
97	Can add goods issue	25	add_goodsissue
98	Can change goods issue	25	change_goodsissue
99	Can delete goods issue	25	delete_goodsissue
100	Can view goods issue	25	view_goodsissue
101	Can add rework order	26	add_reworkorder
102	Can change rework order	26	change_reworkorder
103	Can delete rework order	26	delete_reworkorder
104	Can view rework order	26	view_reworkorder
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: customer_customer; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.customer_customer (customer_id, email_address, phone_number, address_line1, address_line2, city, postal_code, country, customer_type, status, debt, gl_account_id_id, name) FROM stdin;
66	contact@meditechph.com	+63-2-555-1001	123 Health Avenue	Suite 500	Manila	1000	Philippines	Client	Active	1500.00	71	MediTech Solutions Inc.
67	info@philcaremed.com	+63-2-555-1002	456 Wellness St.	\N	Quezon City	1101	Philippines	Prospect	Active	500.00	72	PhilCare Medical Supplies
68	support@lifelinediag.com	+63-2-555-1003	789 Diagnostic Road	Floor 2	Cebu City	6000	Philippines	Lead	Active	0.00	73	LifeLine Diagnostics
69	sales@biopharmph.com	+63-2-555-1004	101 Pharma Park	\N	Makati	1200	Philippines	Client	Active	2000.00	74	BioPharm Innovations
70	contact@wellnesspharma.com	+63-2-555-1005	202 Medical Blvd	\N	Davao City	8000	Philippines	Prospect	Inactive	300.00	75	Wellness Pharma Corp.
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	agreement	blanketagreement
8	agreement	blanketagreementitems
9	CRM	campaigns
10	CRM	leads
11	CRM	campaigncontacts
12	CRM	opportunities
13	CRM	ticket
14	CRM	ticketconvo
15	customer	customer
16	order	orders
17	quotation	quotation
18	quotation	quotationitems
19	misc	chartofaccounts
20	misc	employee
21	misc	policies
22	misc	generalledgeraccounts
23	misc	product
24	misc	businesspartnermaster
25	misc	goodsissue
26	misc	reworkorder
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	misc	0001_initial	2025-03-18 10:43:43.803812+08
2	misc	0002_product_stock	2025-03-18 10:43:43.806151+08
3	misc	0003_businesspartnermaster	2025-03-18 10:43:43.811969+08
4	customer	0001_initial	2025-03-18 10:43:43.824042+08
5	customer	0002_customer_name	2025-03-18 10:43:43.827456+08
6	customer	0003_alter_customer_address_line2	2025-03-18 10:43:43.831171+08
7	customer	0004_alter_customer_city_alter_customer_country_and_more	2025-03-18 10:43:43.863978+08
8	customer	0005_alter_customer_gl_account_id	2025-03-18 10:43:43.875437+08
9	CRM	0001_initial	2025-03-18 10:43:43.90029+08
10	CRM	0002_alter_leads_status	2025-03-18 10:43:43.902903+08
11	CRM	0003_alter_campaigncontacts_campaign_id_and_more	2025-03-18 10:43:43.917781+08
12	CRM	0004_ticket_ticketconvo	2025-03-18 10:43:43.942358+08
13	CRM	0005_campaigns_status	2025-03-18 10:43:43.945861+08
14	CRM	0006_alter_campaigns_end_date_alter_campaigns_start_date	2025-03-18 10:43:43.95194+08
15	CRM	0007_campaigncontacts_response_status	2025-03-18 10:43:43.96229+08
16	CRM	0008_remove_campaigncontacts_campcontact_id	2025-03-18 10:43:43.965421+08
17	CRM	0009_alter_campaigncontacts_campaign_id	2025-03-18 10:43:43.977749+08
18	contenttypes	0001_initial	2025-03-18 10:43:43.983591+08
19	auth	0001_initial	2025-03-18 10:43:44.020978+08
20	admin	0001_initial	2025-03-18 10:43:44.032839+08
21	admin	0002_logentry_remove_auto_add	2025-03-18 10:43:44.039009+08
22	admin	0003_logentry_add_action_flag_choices	2025-03-18 10:43:44.043826+08
23	agreement	0001_initial	2025-03-18 10:43:44.068848+08
24	contenttypes	0002_remove_content_type_name	2025-03-18 10:43:44.087466+08
25	auth	0002_alter_permission_name_max_length	2025-03-18 10:43:44.091482+08
26	auth	0003_alter_user_email_max_length	2025-03-18 10:43:44.099622+08
27	auth	0004_alter_user_username_opts	2025-03-18 10:43:44.104311+08
28	auth	0005_alter_user_last_login_null	2025-03-18 10:43:44.109542+08
29	auth	0006_require_contenttypes_0002	2025-03-18 10:43:44.110551+08
30	auth	0007_alter_validators_add_error_messages	2025-03-18 10:43:44.112779+08
31	auth	0008_alter_user_username_max_length	2025-03-18 10:43:44.122696+08
32	auth	0009_alter_user_last_name_max_length	2025-03-18 10:43:44.126123+08
33	auth	0010_alter_group_name_max_length	2025-03-18 10:43:44.133931+08
34	auth	0011_update_proxy_permissions	2025-03-18 10:43:44.139978+08
35	auth	0012_alter_user_first_name_max_length	2025-03-18 10:43:44.150754+08
36	misc	0004_goodsissue_reworkorder	2025-03-18 10:43:44.154052+08
37	quotation	0001_initial	2025-03-18 10:43:44.182694+08
38	quotation	0002_rename_salesresp_id_quotation_salesrep_id	2025-03-18 10:43:44.196587+08
39	quotation	0003_alter_quotationitems_table	2025-03-18 10:43:44.2006+08
40	quotation	0004_alter_quotation_type_and_more	2025-03-18 10:43:44.217499+08
41	quotation	0005_alter_quotation_customer_id_and_more	2025-03-18 10:43:44.26137+08
42	order	0001_initial	2025-03-18 10:43:44.28526+08
43	sessions	0001_initial	2025-03-18 10:43:44.292796+08
44	CRM	0010_alter_campaigns_end_date_alter_campaigns_start_date_and_more	2025-03-18 10:56:37.368838+08
45	agreement	0002_alter_blanketagreement_end_date_and_more	2025-03-18 10:56:37.404244+08
46	misc	0005_alter_goodsissue_issue_date_and_more	2025-03-18 10:56:37.427172+08
47	order	0002_alter_orders_order_date	2025-03-18 10:56:37.438523+08
48	quotation	0006_alter_quotation_date_issued	2025-03-18 10:56:37.445533+08
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: misc_businesspartnermaster; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.misc_businesspartnermaster (partner_id, partner_name) FROM stdin;
10	Medical Equipment Inc.
11	Sample Corporation
12	Testing Ltd.
\.


--
-- Data for Name: misc_chartofaccounts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.misc_chartofaccounts (account_code, account_name) FROM stdin;
66	Medical Equipment Inc.
67	The Best Medical Corporation.
68	Talipapa Hospital.
69	Philippine General Hospital
70	Manila Hospital
\.


--
-- Data for Name: misc_employee; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.misc_employee (employee_id, first_name, last_name, email, phone, job_title) FROM stdin;
31	Rafael Sebastian	Torres	rafael@kinetiq.ph	09123456789	Sales Representative
32	Juan Paolo	Dionisio	paolo@kinetiq.ph	09123456789	Sales Representative
33	Princess Nicole	Gregorio	princess@kinetiq.ph	09123456789	Sales Representative
\.


--
-- Data for Name: misc_generalledgeraccounts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.misc_generalledgeraccounts (gl_account_id, account_name, account_code_id) FROM stdin;
71	Medical Equipment Inc.	66
72	The Best Medical Corporation..	67
73	Talipapa Hospital	68
74	Philippine General Hospital	69
75	Manila Hospital	70
\.


--
-- Data for Name: misc_goodsissue; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.misc_goodsissue (goods_issue_id, issue_date) FROM stdin;
\.


--
-- Data for Name: misc_policies; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.misc_policies (policy_id, policy_name, description, effective_date) FROM stdin;
35	Policy 1	First Policy	2025-03-18 00:00:00+08
36	Policy 2	Second Policy	2025-05-02 00:00:00+08
37	Policy 3	Third Policy	2024-01-01 00:00:00+08
\.


--
-- Data for Name: misc_product; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.misc_product (product_id, product_name, description, unit_of_measure, policy_id_id, stock) FROM stdin;
52	Surgical Scalpel	Precision Cutting Tool	pcs	35	10
53	A9	Used for critical patient or longer surgery, close-loop anesthesia.	kg	36	40
54	BeneVision N1	Portable patient monitor for continuous vital signs monitoring.	kg	36	120
55	HyLED 200 M	Surgical light for operating room illumination.	kg\t	35	4
56	Lumis 150 VPAP	Ventilator providing variable positive airway pressure for respiratory support.	kg	37	10
\.


--
-- Data for Name: misc_reworkorder; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.misc_reworkorder (rework_id, rework_status, rework_date, expected_completion) FROM stdin;
\.


--
-- Data for Name: order_orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.order_orders (order_id, order_date, order_status, order_type, agreement_id_id, customer_id_id, goods_issue_id_id, quotation_id_id, rework_id_id, salesrep_id_id) FROM stdin;
\.


--
-- Data for Name: quotation_quotation; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.quotation_quotation (quotation_id, date_issued, total_amount, type, status, customer_id_id, salesrep_id_id) FROM stdin;
92	2025-03-18 00:00:00+08	250000.00	Project Based	Pending	66	31
93	2025-03-18 00:00:00+08	180000.00	Non-Project Based	Approved	67	32
94	2025-03-18 00:00:00+08	12000.00	Service	Rejected	68	33
95	2025-03-18 00:00:00+08	300000.00	Project Based	Approved	69	31
96	2025-03-18 00:00:00+08	15000.00	Non-Project Based	Pending	70	32
97	2025-03-18 00:00:00+08	22000.00	Service	Approved	66	33
98	2025-03-18 00:00:00+08	350000.00	Project Based	Rejected	67	31
99	2025-03-18 00:00:00+08	290000.00	Non-Project Based	Approved	68	32
100	2025-03-18 00:00:00+08	31000.00	Service	Pending	69	33
101	2025-03-18 00:00:00+08	400000.00	Project Based	Approved	70	31
\.


--
-- Data for Name: quotation_quotationitems; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.quotation_quotationitems (qitems_id, quantity, unit_price, total_price, product_id_id, quotation_id_id) FROM stdin;
181	5	1200.00	6000.00	52	92
182	10	500.00	5000.00	52	93
183	50	150.00	7500.00	53	92
184	2	3000.00	6000.00	54	94
185	20	100.00	2000.00	55	95
186	200	50.00	10000.00	56	96
187	3	400.00	1200.00	52	97
188	5	700.00	3500.00	53	98
189	2	900.00	1800.00	54	99
190	100	30.00	3000.00	55	100
\.


--
-- Name: CRM_campaigncontacts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."CRM_campaigncontacts_id_seq"', 40, true);


--
-- Name: CRM_campaigns_campaign_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."CRM_campaigns_campaign_id_seq"', 40, true);


--
-- Name: CRM_leads_lead_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."CRM_leads_lead_id_seq"', 50, true);


--
-- Name: CRM_opportunities_opportunity_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."CRM_opportunities_opportunity_id_seq"', 32, true);


--
-- Name: CRM_ticket_ticket_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."CRM_ticket_ticket_id_seq"', 20, true);


--
-- Name: CRM_ticketconvo_convo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."CRM_ticketconvo_convo_id_seq"', 20, true);


--
-- Name: agreement_blanketagreement_agreement_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.agreement_blanketagreement_agreement_id_seq', 1, false);


--
-- Name: agreement_blanketagreementitems_agreement_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.agreement_blanketagreementitems_agreement_items_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 104, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, false);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: customer_customer_customer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.customer_customer_customer_id_seq', 70, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 26, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 48, true);


--
-- Name: misc_businesspartnermaster_partner_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.misc_businesspartnermaster_partner_id_seq', 12, true);


--
-- Name: misc_chartofaccounts_account_code_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.misc_chartofaccounts_account_code_seq', 70, true);


--
-- Name: misc_employee_employee_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.misc_employee_employee_id_seq', 33, true);


--
-- Name: misc_generalledgeraccounts_gl_account_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.misc_generalledgeraccounts_gl_account_id_seq', 75, true);


--
-- Name: misc_goodsissue_goods_issue_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.misc_goodsissue_goods_issue_id_seq', 1, false);


--
-- Name: misc_policies_policy_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.misc_policies_policy_id_seq', 37, true);


--
-- Name: misc_product_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.misc_product_product_id_seq', 56, true);


--
-- Name: misc_reworkorder_rework_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.misc_reworkorder_rework_id_seq', 1, false);


--
-- Name: order_orders_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.order_orders_order_id_seq', 1, false);


--
-- Name: quotation_quotation_quotation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.quotation_quotation_quotation_id_seq', 101, true);


--
-- Name: quotation_quotationitems_qitems_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.quotation_quotationitems_qitems_id_seq', 190, true);


--
-- Name: CRM_campaigncontacts CRM_campaigncontacts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CRM_campaigncontacts"
    ADD CONSTRAINT "CRM_campaigncontacts_pkey" PRIMARY KEY (id);


--
-- Name: CRM_campaigns CRM_campaigns_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CRM_campaigns"
    ADD CONSTRAINT "CRM_campaigns_pkey" PRIMARY KEY (campaign_id);


--
-- Name: CRM_leads CRM_leads_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CRM_leads"
    ADD CONSTRAINT "CRM_leads_pkey" PRIMARY KEY (lead_id);


--
-- Name: CRM_opportunities CRM_opportunities_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CRM_opportunities"
    ADD CONSTRAINT "CRM_opportunities_pkey" PRIMARY KEY (opportunity_id);


--
-- Name: CRM_ticket CRM_ticket_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CRM_ticket"
    ADD CONSTRAINT "CRM_ticket_pkey" PRIMARY KEY (ticket_id);


--
-- Name: CRM_ticketconvo CRM_ticketconvo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CRM_ticketconvo"
    ADD CONSTRAINT "CRM_ticketconvo_pkey" PRIMARY KEY (convo_id);


--
-- Name: agreement_blanketagreement agreement_blanketagreement_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.agreement_blanketagreement
    ADD CONSTRAINT agreement_blanketagreement_pkey PRIMARY KEY (agreement_id);


--
-- Name: agreement_blanketagreementitems agreement_blanketagreementitems_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.agreement_blanketagreementitems
    ADD CONSTRAINT agreement_blanketagreementitems_pkey PRIMARY KEY (agreement_items_id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: customer_customer customer_customer_email_address_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer_customer
    ADD CONSTRAINT customer_customer_email_address_key UNIQUE (email_address);


--
-- Name: customer_customer customer_customer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer_customer
    ADD CONSTRAINT customer_customer_pkey PRIMARY KEY (customer_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: misc_businesspartnermaster misc_businesspartnermaster_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.misc_businesspartnermaster
    ADD CONSTRAINT misc_businesspartnermaster_pkey PRIMARY KEY (partner_id);


--
-- Name: misc_chartofaccounts misc_chartofaccounts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.misc_chartofaccounts
    ADD CONSTRAINT misc_chartofaccounts_pkey PRIMARY KEY (account_code);


--
-- Name: misc_employee misc_employee_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.misc_employee
    ADD CONSTRAINT misc_employee_pkey PRIMARY KEY (employee_id);


--
-- Name: misc_generalledgeraccounts misc_generalledgeraccounts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.misc_generalledgeraccounts
    ADD CONSTRAINT misc_generalledgeraccounts_pkey PRIMARY KEY (gl_account_id);


--
-- Name: misc_goodsissue misc_goodsissue_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.misc_goodsissue
    ADD CONSTRAINT misc_goodsissue_pkey PRIMARY KEY (goods_issue_id);


--
-- Name: misc_policies misc_policies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.misc_policies
    ADD CONSTRAINT misc_policies_pkey PRIMARY KEY (policy_id);


--
-- Name: misc_product misc_product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.misc_product
    ADD CONSTRAINT misc_product_pkey PRIMARY KEY (product_id);


--
-- Name: misc_reworkorder misc_reworkorder_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.misc_reworkorder
    ADD CONSTRAINT misc_reworkorder_pkey PRIMARY KEY (rework_id);


--
-- Name: order_orders order_orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_orders
    ADD CONSTRAINT order_orders_pkey PRIMARY KEY (order_id);


--
-- Name: quotation_quotation quotation_quotation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quotation_quotation
    ADD CONSTRAINT quotation_quotation_pkey PRIMARY KEY (quotation_id);


--
-- Name: quotation_quotationitems quotation_quotationitems_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quotation_quotationitems
    ADD CONSTRAINT quotation_quotationitems_pkey PRIMARY KEY (qitems_id);


--
-- Name: CRM_campaigncontacts_campaign_id_id_c35e035a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "CRM_campaigncontacts_campaign_id_id_c35e035a" ON public."CRM_campaigncontacts" USING btree (campaign_id_id);


--
-- Name: CRM_campaigncontacts_lead_id_id_dafc9ae8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "CRM_campaigncontacts_lead_id_id_dafc9ae8" ON public."CRM_campaigncontacts" USING btree (lead_id_id);


--
-- Name: CRM_leads_salesrep_id_id_222dfcad; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "CRM_leads_salesrep_id_id_222dfcad" ON public."CRM_leads" USING btree (salesrep_id_id);


--
-- Name: CRM_opportunities_customer_id_id_ad61114f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "CRM_opportunities_customer_id_id_ad61114f" ON public."CRM_opportunities" USING btree (customer_id_id);


--
-- Name: CRM_opportunities_partner_id_id_9cab44a5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "CRM_opportunities_partner_id_id_9cab44a5" ON public."CRM_opportunities" USING btree (partner_id_id);


--
-- Name: CRM_opportunities_salesrep_id_id_019ed8fc; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "CRM_opportunities_salesrep_id_id_019ed8fc" ON public."CRM_opportunities" USING btree (salesrep_id_id);


--
-- Name: CRM_ticket_customer_id_id_1934d054; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "CRM_ticket_customer_id_id_1934d054" ON public."CRM_ticket" USING btree (customer_id_id);


--
-- Name: CRM_ticket_salesrep_id_id_0aa4ae9d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "CRM_ticket_salesrep_id_id_0aa4ae9d" ON public."CRM_ticket" USING btree (salesrep_id_id);


--
-- Name: CRM_ticketconvo_ticket_id_id_e4002fd4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "CRM_ticketconvo_ticket_id_id_e4002fd4" ON public."CRM_ticketconvo" USING btree (ticket_id_id);


--
-- Name: agreement_blanketagreement_customer_id_id_df6b53ef; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX agreement_blanketagreement_customer_id_id_df6b53ef ON public.agreement_blanketagreement USING btree (customer_id_id);


--
-- Name: agreement_blanketagreement_salesrep_id_id_37e2663f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX agreement_blanketagreement_salesrep_id_id_37e2663f ON public.agreement_blanketagreement USING btree (salesrep_id_id);


--
-- Name: agreement_blanketagreementitems_agreement_id_id_5a45be83; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX agreement_blanketagreementitems_agreement_id_id_5a45be83 ON public.agreement_blanketagreementitems USING btree (agreement_id_id);


--
-- Name: agreement_blanketagreementitems_product_id_id_7e9d8fcf; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX agreement_blanketagreementitems_product_id_id_7e9d8fcf ON public.agreement_blanketagreementitems USING btree (product_id_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: customer_customer_gl_account_id_id_3b46063e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX customer_customer_gl_account_id_id_3b46063e ON public.customer_customer USING btree (gl_account_id_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: misc_generalledgeraccounts_account_code_id_3a80a8a6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX misc_generalledgeraccounts_account_code_id_3a80a8a6 ON public.misc_generalledgeraccounts USING btree (account_code_id);


--
-- Name: misc_product_policy_id_id_99bca2b4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX misc_product_policy_id_id_99bca2b4 ON public.misc_product USING btree (policy_id_id);


--
-- Name: order_orders_agreement_id_id_2cff336b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX order_orders_agreement_id_id_2cff336b ON public.order_orders USING btree (agreement_id_id);


--
-- Name: order_orders_customer_id_id_e0e08ded; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX order_orders_customer_id_id_e0e08ded ON public.order_orders USING btree (customer_id_id);


--
-- Name: order_orders_goods_issue_id_id_15597aa7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX order_orders_goods_issue_id_id_15597aa7 ON public.order_orders USING btree (goods_issue_id_id);


--
-- Name: order_orders_quotation_id_id_00c24929; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX order_orders_quotation_id_id_00c24929 ON public.order_orders USING btree (quotation_id_id);


--
-- Name: order_orders_rework_id_id_25a88548; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX order_orders_rework_id_id_25a88548 ON public.order_orders USING btree (rework_id_id);


--
-- Name: order_orders_salesrep_id_id_f8c8d676; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX order_orders_salesrep_id_id_f8c8d676 ON public.order_orders USING btree (salesrep_id_id);


--
-- Name: quotation_quotation_customer_id_id_4b97d73c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX quotation_quotation_customer_id_id_4b97d73c ON public.quotation_quotation USING btree (customer_id_id);


--
-- Name: quotation_quotation_salesresp_id_id_6f7ff176; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX quotation_quotation_salesresp_id_id_6f7ff176 ON public.quotation_quotation USING btree (salesrep_id_id);


--
-- Name: quotation_quotationitems_product_id_id_fbfb2aae; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX quotation_quotationitems_product_id_id_fbfb2aae ON public.quotation_quotationitems USING btree (product_id_id);


--
-- Name: quotation_quotationitems_quotation_id_id_b0a13528; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX quotation_quotationitems_quotation_id_id_b0a13528 ON public.quotation_quotationitems USING btree (quotation_id_id);


--
-- Name: CRM_campaigncontacts CRM_campaigncontacts_campaign_id_id_c35e035a_fk_CRM_campa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CRM_campaigncontacts"
    ADD CONSTRAINT "CRM_campaigncontacts_campaign_id_id_c35e035a_fk_CRM_campa" FOREIGN KEY (campaign_id_id) REFERENCES public."CRM_campaigns"(campaign_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: CRM_campaigncontacts CRM_campaigncontacts_lead_id_id_dafc9ae8_fk_CRM_leads_lead_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CRM_campaigncontacts"
    ADD CONSTRAINT "CRM_campaigncontacts_lead_id_id_dafc9ae8_fk_CRM_leads_lead_id" FOREIGN KEY (lead_id_id) REFERENCES public."CRM_leads"(lead_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: CRM_leads CRM_leads_salesrep_id_id_222dfcad_fk_misc_employee_employee_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CRM_leads"
    ADD CONSTRAINT "CRM_leads_salesrep_id_id_222dfcad_fk_misc_employee_employee_id" FOREIGN KEY (salesrep_id_id) REFERENCES public.misc_employee(employee_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: CRM_opportunities CRM_opportunities_customer_id_id_ad61114f_fk_customer_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CRM_opportunities"
    ADD CONSTRAINT "CRM_opportunities_customer_id_id_ad61114f_fk_customer_" FOREIGN KEY (customer_id_id) REFERENCES public.customer_customer(customer_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: CRM_opportunities CRM_opportunities_partner_id_id_9cab44a5_fk_misc_busi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CRM_opportunities"
    ADD CONSTRAINT "CRM_opportunities_partner_id_id_9cab44a5_fk_misc_busi" FOREIGN KEY (partner_id_id) REFERENCES public.misc_businesspartnermaster(partner_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: CRM_opportunities CRM_opportunities_salesrep_id_id_019ed8fc_fk_misc_empl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CRM_opportunities"
    ADD CONSTRAINT "CRM_opportunities_salesrep_id_id_019ed8fc_fk_misc_empl" FOREIGN KEY (salesrep_id_id) REFERENCES public.misc_employee(employee_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: CRM_ticket CRM_ticket_customer_id_id_1934d054_fk_customer_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CRM_ticket"
    ADD CONSTRAINT "CRM_ticket_customer_id_id_1934d054_fk_customer_" FOREIGN KEY (customer_id_id) REFERENCES public.customer_customer(customer_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: CRM_ticket CRM_ticket_salesrep_id_id_0aa4ae9d_fk_misc_employee_employee_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CRM_ticket"
    ADD CONSTRAINT "CRM_ticket_salesrep_id_id_0aa4ae9d_fk_misc_employee_employee_id" FOREIGN KEY (salesrep_id_id) REFERENCES public.misc_employee(employee_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: CRM_ticketconvo CRM_ticketconvo_ticket_id_id_e4002fd4_fk_CRM_ticket_ticket_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CRM_ticketconvo"
    ADD CONSTRAINT "CRM_ticketconvo_ticket_id_id_e4002fd4_fk_CRM_ticket_ticket_id" FOREIGN KEY (ticket_id_id) REFERENCES public."CRM_ticket"(ticket_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: agreement_blanketagreementitems agreement_blanketagr_agreement_id_id_5a45be83_fk_agreement; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.agreement_blanketagreementitems
    ADD CONSTRAINT agreement_blanketagr_agreement_id_id_5a45be83_fk_agreement FOREIGN KEY (agreement_id_id) REFERENCES public.agreement_blanketagreement(agreement_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: agreement_blanketagreement agreement_blanketagr_customer_id_id_df6b53ef_fk_customer_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.agreement_blanketagreement
    ADD CONSTRAINT agreement_blanketagr_customer_id_id_df6b53ef_fk_customer_ FOREIGN KEY (customer_id_id) REFERENCES public.customer_customer(customer_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: agreement_blanketagreementitems agreement_blanketagr_product_id_id_7e9d8fcf_fk_misc_prod; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.agreement_blanketagreementitems
    ADD CONSTRAINT agreement_blanketagr_product_id_id_7e9d8fcf_fk_misc_prod FOREIGN KEY (product_id_id) REFERENCES public.misc_product(product_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: agreement_blanketagreement agreement_blanketagr_salesrep_id_id_37e2663f_fk_misc_empl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.agreement_blanketagreement
    ADD CONSTRAINT agreement_blanketagr_salesrep_id_id_37e2663f_fk_misc_empl FOREIGN KEY (salesrep_id_id) REFERENCES public.misc_employee(employee_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: customer_customer customer_customer_gl_account_id_id_3b46063e_fk_misc_gene; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer_customer
    ADD CONSTRAINT customer_customer_gl_account_id_id_3b46063e_fk_misc_gene FOREIGN KEY (gl_account_id_id) REFERENCES public.misc_generalledgeraccounts(gl_account_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: misc_generalledgeraccounts misc_generalledgerac_account_code_id_3a80a8a6_fk_misc_char; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.misc_generalledgeraccounts
    ADD CONSTRAINT misc_generalledgerac_account_code_id_3a80a8a6_fk_misc_char FOREIGN KEY (account_code_id) REFERENCES public.misc_chartofaccounts(account_code) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: misc_product misc_product_policy_id_id_99bca2b4_fk_misc_policies_policy_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.misc_product
    ADD CONSTRAINT misc_product_policy_id_id_99bca2b4_fk_misc_policies_policy_id FOREIGN KEY (policy_id_id) REFERENCES public.misc_policies(policy_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: order_orders order_orders_agreement_id_id_2cff336b_fk_agreement; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_orders
    ADD CONSTRAINT order_orders_agreement_id_id_2cff336b_fk_agreement FOREIGN KEY (agreement_id_id) REFERENCES public.agreement_blanketagreement(agreement_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: order_orders order_orders_customer_id_id_e0e08ded_fk_customer_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_orders
    ADD CONSTRAINT order_orders_customer_id_id_e0e08ded_fk_customer_ FOREIGN KEY (customer_id_id) REFERENCES public.customer_customer(customer_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: order_orders order_orders_goods_issue_id_id_15597aa7_fk_misc_good; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_orders
    ADD CONSTRAINT order_orders_goods_issue_id_id_15597aa7_fk_misc_good FOREIGN KEY (goods_issue_id_id) REFERENCES public.misc_goodsissue(goods_issue_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: order_orders order_orders_quotation_id_id_00c24929_fk_quotation; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_orders
    ADD CONSTRAINT order_orders_quotation_id_id_00c24929_fk_quotation FOREIGN KEY (quotation_id_id) REFERENCES public.quotation_quotation(quotation_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: order_orders order_orders_rework_id_id_25a88548_fk_misc_rewo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_orders
    ADD CONSTRAINT order_orders_rework_id_id_25a88548_fk_misc_rewo FOREIGN KEY (rework_id_id) REFERENCES public.misc_reworkorder(rework_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: order_orders order_orders_salesrep_id_id_f8c8d676_fk_misc_empl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_orders
    ADD CONSTRAINT order_orders_salesrep_id_id_f8c8d676_fk_misc_empl FOREIGN KEY (salesrep_id_id) REFERENCES public.misc_employee(employee_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: quotation_quotation quotation_quotation_customer_id_id_4b97d73c_fk_customer_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quotation_quotation
    ADD CONSTRAINT quotation_quotation_customer_id_id_4b97d73c_fk_customer_ FOREIGN KEY (customer_id_id) REFERENCES public.customer_customer(customer_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: quotation_quotation quotation_quotation_salesrep_id_id_39a429a6_fk_misc_empl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quotation_quotation
    ADD CONSTRAINT quotation_quotation_salesrep_id_id_39a429a6_fk_misc_empl FOREIGN KEY (salesrep_id_id) REFERENCES public.misc_employee(employee_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: quotation_quotationitems quotation_quotationi_product_id_id_fbfb2aae_fk_misc_prod; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quotation_quotationitems
    ADD CONSTRAINT quotation_quotationi_product_id_id_fbfb2aae_fk_misc_prod FOREIGN KEY (product_id_id) REFERENCES public.misc_product(product_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: quotation_quotationitems quotation_quotationi_quotation_id_id_b0a13528_fk_quotation; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quotation_quotationitems
    ADD CONSTRAINT quotation_quotationi_quotation_id_id_b0a13528_fk_quotation FOREIGN KEY (quotation_id_id) REFERENCES public.quotation_quotation(quotation_id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

