# Generated by Django 5.1.6 on 2025-03-17 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('account_code', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_name', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(max_length=255)),
                ('last_name', models.TextField(max_length=255)),
                ('email', models.TextField(max_length=255)),
                ('phone', models.TextField(max_length=255)),
                ('job_title', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('policy_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('policy_name', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('effective_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralLedgerAccounts',
            fields=[
                ('gl_account_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_name', models.TextField(max_length=255)),
                ('account_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.chartofaccounts')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('unit_of_measure', models.TextField(default='kg', max_length=255)),
                ('policy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.policies')),
            ],
        ),
    ]
