# Generated by Django 5.1.6 on 2025-03-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartnerMaster',
            fields=[
                ('partner_id', models.AutoField(primary_key=True, serialize=False)),
                ('partner_name', models.CharField(max_length=255)),
            ],
        ),
    ]
