# Generated by Django 5.1.6 on 2025-03-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_businesspartnermaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsIssue',
            fields=[
                ('goods_issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ReworkOrder',
            fields=[
                ('rework_id', models.AutoField(primary_key=True, serialize=False)),
                ('rework_status', models.TextField()),
                ('rework_date', models.DateField()),
                ('expected_completion', models.DateField()),
            ],
        ),
    ]
