# Generated by Django 5.1.6 on 2025-03-18 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0004_goodsissue_reworkorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsissue',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 10, 56, 34, 422006)),
        ),
        migrations.AlterField(
            model_name='policies',
            name='effective_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 10, 56, 34, 420586)),
        ),
        migrations.AlterField(
            model_name='reworkorder',
            name='expected_completion',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 10, 56, 34, 421883)),
        ),
        migrations.AlterField(
            model_name='reworkorder',
            name='rework_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 10, 56, 34, 421590)),
        ),
    ]
