# Generated by Django 5.1.6 on 2025-03-18 04:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0005_alter_goodsissue_issue_date_and_more'),
        ('order', '0002_alter_orders_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterials',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_of_measure', models.CharField(default='kg')),
            ],
        ),
        migrations.AlterField(
            model_name='goodsissue',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 12, 8, 9, 430148)),
        ),
        migrations.AlterField(
            model_name='policies',
            name='effective_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 12, 8, 9, 430148)),
        ),
        migrations.AlterField(
            model_name='reworkorder',
            name='expected_completion',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 12, 8, 9, 430148)),
        ),
        migrations.AlterField(
            model_name='reworkorder',
            name='rework_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 12, 8, 9, 430148)),
        ),
        migrations.CreateModel(
            name='NonProjectOrderPricing',
            fields=[
                ('non_project_costing_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_of_raw_materials', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp_base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orders')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_price', to='misc.product')),
            ],
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('bom_id', models.AutoField(primary_key=True, serialize=False)),
                ('specific_notes', models.TextField(blank=True, null=True)),
                ('quantity_of_unit', models.IntegerField(default=1)),
                ('cost_per_raw_material', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost_of_raw_materials', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom', to='misc.product')),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.rawmaterials')),
            ],
        ),
    ]
