# Generated by Django 5.1.6 on 2025-03-18 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0008_alter_goodsissue_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsissue',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 12, 23, 53, 380905)),
        ),
        migrations.AlterField(
            model_name='policies',
            name='effective_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 12, 23, 53, 380905)),
        ),
        migrations.AlterField(
            model_name='reworkorder',
            name='expected_completion',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 12, 23, 53, 380905)),
        ),
        migrations.AlterField(
            model_name='reworkorder',
            name='rework_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 12, 23, 53, 380905)),
        ),
    ]
