# Generated by Django 5.1.6 on 2025-03-18 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0013_alter_goodsissue_issue_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalledgeraccounts',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=20000, max_digits=10),
        ),
        migrations.AddField(
            model_name='generalledgeraccounts',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='goodsissue',
            name='issue_by',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 15, 50, 11, 3146)),
        ),
        migrations.AlterField(
            model_name='goodsissue',
            name='issue_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 18, 15, 50, 11, 3146), null=True),
        ),
        migrations.AlterField(
            model_name='policies',
            name='effective_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 15, 50, 11, 2109)),
        ),
        migrations.AlterField(
            model_name='reworkorder',
            name='expected_completion',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 15, 50, 11, 3146)),
        ),
        migrations.AlterField(
            model_name='reworkorder',
            name='rework_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 15, 50, 11, 3146)),
        ),
    ]
