# Generated by Django 5.1.6 on 2025-03-18 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0014_generalledgeraccounts_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsissue',
            name='issue_by',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 15, 57, 34, 255414)),
        ),
        migrations.AlterField(
            model_name='goodsissue',
            name='issue_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 18, 15, 57, 34, 255414), null=True),
        ),
        migrations.AlterField(
            model_name='policies',
            name='effective_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 15, 57, 34, 255414)),
        ),
        migrations.AlterField(
            model_name='reworkorder',
            name='expected_completion',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 15, 57, 34, 255414)),
        ),
        migrations.AlterField(
            model_name='reworkorder',
            name='rework_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 15, 57, 34, 255414)),
        ),
    ]
