# Generated by Django 5.1.6 on 2025-03-17 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0005_alter_customer_gl_account_id'),
        ('misc', '0003_businesspartnermaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlanketAgreement',
            fields=[
                ('agreement_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.TextField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled')])),
                ('description', models.CharField(max_length=255)),
                ('signed_date', models.DateField()),
                ('agreement_method', models.TextField(choices=[('Written', 'Written'), ('Oral', 'Oral'), ('Electronic', 'Electronic')])),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('salesrep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.employee')),
            ],
        ),
        migrations.CreateModel(
            name='BlanketAgreementItems',
            fields=[
                ('agreement_items_id', models.AutoField(primary_key=True, serialize=False)),
                ('agreed_quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agreement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='agreement.blanketagreement')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.product')),
            ],
        ),
    ]
