# Generated by Django 5.1.6 on 2025-03-18 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blanketagreement',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 10, 56, 34, 398643)),
        ),
        migrations.AlterField(
            model_name='blanketagreement',
            name='signed_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 10, 56, 34, 398643)),
        ),
        migrations.AlterField(
            model_name='blanketagreement',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 10, 56, 34, 398643)),
        ),
    ]
