# Generated by Django 5.1.6 on 2025-03-18 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0009_alter_blanketagreement_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blanketagreement',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 15, 0, 54, 317097)),
        ),
        migrations.AlterField(
            model_name='blanketagreement',
            name='signed_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 15, 0, 54, 317097)),
        ),
        migrations.AlterField(
            model_name='blanketagreement',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 15, 0, 54, 317097)),
        ),
    ]
