# Generated by Django 5.1.6 on 2025-03-18 07:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0010_alter_orders_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoices',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateTimeField(default=datetime.datetime(2025, 3, 18, 15, 0, 54, 317097))),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_status', models.TextField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], default='Pending')),
                ('payment_status', models.TextField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Partial', 'Partial')], default='Unpaid')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='order.orders')),
            ],
        ),
    ]
