# Generated by Django 5.1.6 on 2025-03-18 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesCosting',
            fields=[
                ('sales_costing_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 3, 18, 12, 8, 9, 414529))),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
