# Generated by Django 5.1.6 on 2025-03-18 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costing', '0001_initial'),
        ('misc', '0006_rawmaterials_alter_goodsissue_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salescosting',
            name='bom_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.bom'),
        ),
        migrations.AddField(
            model_name='salescosting',
            name='non_project_costing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.nonprojectorderpricing'),
        ),
    ]
