# Generated by Django 5.1.6 on 2025-03-18 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salescosting',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 12, 13, 58, 223355)),
        ),
    ]
