# Generated by Django 5.1.6 on 2025-03-18 04:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0005_alter_salescosting_created_at'),
        ('misc', '0010_alter_goodsissue_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salescosting',
            name='bom_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.bom'),
        ),
        migrations.AlterField(
            model_name='salescosting',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 12, 31, 8, 93788)),
        ),
        migrations.AlterField(
            model_name='salescosting',
            name='non_project_costing_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.nonprojectorderpricing'),
        ),
    ]
