# Generated by Django 5.1.6 on 2025-03-18 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0006_alter_salescosting_bom_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salescosting',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 13, 9, 10, 694975)),
        ),
    ]
