# Generated by Django 5.1.6 on 2025-03-18 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0008_alter_salescosting_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salescosting',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 15, 0, 54, 317097)),
        ),
    ]
