# Generated by Django 5.1.6 on 2025-03-17 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agreement', '0001_initial'),
        ('customer', '0005_alter_customer_gl_account_id'),
        ('misc', '0004_goodsissue_reworkorder'),
        ('quotation', '0005_alter_quotation_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('order_status', models.TextField(choices=[('Pending', 'Pending'), ('Processed', 'Processed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')])),
                ('order_type', models.TextField(choices=[('Direct', 'Direct'), ('Scheduled', 'Scheduled'), ('Open', 'Open'), ('D3 Sample', 'D3 Sample')])),
                ('agreement_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agreement.blanketagreement')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('goods_issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.goodsissue')),
                ('quotation_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotation.quotation')),
                ('rework_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.reworkorder')),
                ('salesrep_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.employee')),
            ],
        ),
    ]
