# Generated by Django 5.1.6 on 2025-03-18 04:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0001_initial'),
        ('misc', '0006_rawmaterials_alter_goodsissue_issue_date_and_more'),
        ('order', '0002_alter_orders_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 12, 8, 9, 414529)),
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('demand_level', models.TextField(choices=[('Low Demand', 'Low'), ('Medium Demand', 'Medium'), ('High Demand', 'High'), ('Very High Demand', 'Very High'), ('Seasonal Demand', 'Seasonal')])),
                ('markup_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.product')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orders')),
                ('sales_costing_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='costing.salescosting')),
            ],
        ),
    ]
