# Generated by Django 5.1.6 on 2025-03-18 04:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0009_alter_goodsissue_issue_date_and_more'),
        ('order', '0005_alter_orders_order_date_alter_orders_rework_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 12, 23, 53, 365281)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='rework_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.reworkorder'),
        ),
    ]
