# Generated by Django 5.1.6 on 2025-03-18 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_orders_order_date_alter_orders_rework_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 12, 31, 8, 93788)),
        ),
    ]
