# Generated by Django 5.1.6 on 2025-03-18 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_orders_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 13, 9, 10, 694975)),
        ),
    ]
