# Generated by Django 5.1.6 on 2025-03-18 06:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0012_alter_goodsissue_issue_by_and_more'),
        ('order', '0008_alter_orders_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='demand_level',
            field=models.TextField(choices=[('Low Demand', 'Low'), ('Medium Demand', 'Medium'), ('High Demand', 'High'), ('Very High Demand', 'Very High'), ('Seasonal Demand', 'Seasonal')], default='Low Demand'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='goods_issue_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.goodsissue'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 14, 21, 49, 295282)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.TextField(choices=[('Pending', 'Pending'), ('Processed', 'Processed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending'),
        ),
    ]
