# Generated by Django 5.1.6 on 2025-03-18 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_orderitems_demand_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 15, 0, 54, 328677)),
        ),
    ]
