# Generated by Django 5.1.6 on 2025-03-17 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misc', '0002_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('campaign_id', models.AutoField(primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(max_length=255)),
                ('type', models.TextField(choices=[('Email', 'Email'), ('Social Media', 'Social Media'), ('Referral', 'Referral'), ('Advertisement', 'Advertisement')], default='Email')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('lead_id', models.AutoField(primary_key=True, serialize=False)),
                ('lead_name', models.CharField(max_length=255)),
                ('lead_email', models.CharField(max_length=255)),
                ('lead_phonenum', models.CharField(max_length=20)),
                ('source', models.TextField(choices=[('Website', 'Website'), ('Referral', 'Referral'), ('Cold Call', 'Cold Call'), ('Email', 'Email')], default='Website')),
                ('status', models.TextField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('CONVERTED', 'Converted'), ('LOST', 'Lost')], default='NEW')),
                ('salesrep_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.employee')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campcontact_id', models.CharField(max_length=255)),
                ('campaign_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CRM.campaigns')),
                ('lead_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CRM.leads')),
            ],
        ),
    ]
