# Generated by Django 5.1.6 on 2025-03-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='status',
            field=models.TextField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Qualified', 'Qualified'), ('Converted', 'Converted'), ('Lost', 'Lost')], default='New'),
        ),
    ]
