# Generated by Django 5.1.6 on 2025-03-17 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_alter_leads_status'),
        ('customer', '0005_alter_customer_gl_account_id'),
        ('misc', '0003_businesspartnermaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncontacts',
            name='campaign_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='CRM.campaigns'),
        ),
        migrations.AlterField(
            model_name='campaigncontacts',
            name='lead_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='CRM.leads'),
        ),
        migrations.CreateModel(
            name='Opportunities',
            fields=[
                ('opportunity_id', models.AutoField(primary_key=True, serialize=False)),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_closed_date', models.DateField()),
                ('stage', models.TextField(choices=[('Prospecting', 'Prospecting'), ('Negotiation', 'Negotiation'), ('Closed', 'Closed')])),
                ('status', models.TextField(choices=[('Open', 'Open'), ('Won', 'Won'), ('Lost', 'Lost')])),
                ('description', models.TextField()),
                ('reason_lost', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer')),
                ('partner_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.businesspartnermaster')),
                ('salesrep_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.employee')),
            ],
        ),
    ]
