# Generated by Django 5.1.6 on 2025-03-17 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_alter_campaigncontacts_campaign_id_and_more'),
        ('customer', '0005_alter_customer_gl_account_id'),
        ('misc', '0003_businesspartnermaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.TextField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')])),
                ('priority', models.TextField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('salesrep_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.employee')),
            ],
        ),
        migrations.CreateModel(
            name='TicketConvo',
            fields=[
                ('convo_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='CRM.ticket')),
            ],
        ),
    ]
