# Generated by Django 5.1.6 on 2025-03-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_ticket_ticketconvo'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='status',
            field=models.TextField(choices=[('Planned', 'Planned'), ('Active', 'Active'), ('Completed', 'Completed')], default='Active'),
        ),
    ]
