# Generated by Django 5.1.6 on 2025-03-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_campaigns_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
