# Generated by Django 5.1.6 on 2025-03-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0006_alter_campaigns_end_date_alter_campaigns_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncontacts',
            name='response_status',
            field=models.TextField(choices=[('Interested', 'Interested'), ('Not Interested', 'Not Interested'), ('Pending', 'Pending')], default='Pending'),
        ),
    ]
