# Generated by Django 5.1.6 on 2025-03-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0007_campaigncontacts_response_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigncontacts',
            name='campcontact_id',
        ),
    ]
