# Generated by Django 5.1.6 on 2025-03-17 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0008_remove_campaigncontacts_campcontact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncontacts',
            name='campaign_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='CRM.campaigns'),
            preserve_default=False,
        ),
    ]
