# Generated by Django 5.1.6 on 2025-03-18 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0009_alter_campaigncontacts_campaign_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 10, 56, 34, 411477)),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 10, 56, 34, 411477)),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 10, 56, 34, 412481)),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='expected_closed_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 10, 56, 34, 412481)),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='reason_lost',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 10, 56, 34, 413481)),
        ),
        migrations.AlterField(
            model_name='ticketconvo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 10, 56, 34, 413481)),
        ),
    ]
